#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from layout_map import ACTIONS

LAYOUT_MAP = [
    [ACTIONS['KEY']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_4']], [ACTIONS['BIG_GAP'], ACTIONS['OFFSET_4']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY']], [ACTIONS['KEY']], [ACTIONS['END']],

    [ACTIONS['KEY']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_4']], [ACTIONS['BIG_GAP'], ACTIONS['OFFSET_4']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY']], [ACTIONS['KEY']], [ACTIONS['END']],

    [ACTIONS['KEY']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_4']], [ACTIONS['KEY']], [ACTIONS['KEY']], [ACTIONS['GAP']], [ACTIONS['KEY']], [ACTIONS['KEY'], ACTIONS['OFFSET_4']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_2']], [ACTIONS['KEY'], ACTIONS['OFFSET_1']], [ACTIONS['KEY']], [ACTIONS['KEY']], [ACTIONS['END'], ACTIONS['ROW'], ACTIONS['OFFSET_3']],

    [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_5']], [ACTIONS['KEY']], [ACTIONS['KEY']], [ACTIONS['BOTTOM_GAP']], [ACTIONS['KEY']], [ACTIONS['KEY'], ACTIONS['OFFSET_5']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY'], ACTIONS['OFFSET_3']], [ACTIONS['KEY']], [ACTIONS['KEY']]
]

for actions in LAYOUT_MAP:
    item = sum(actions)
    end = ", "

    if ACTIONS['END'] in actions:
        end = ",\n"

    print(hex(item), end=end)

print()
